[2023-04-28T14:57:31.965+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion_DAG.transform_data manual__2023-04-28T14:57:29.074504+00:00 [queued]>
[2023-04-28T14:57:31.978+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion_DAG.transform_data manual__2023-04-28T14:57:29.074504+00:00 [queued]>
[2023-04-28T14:57:31.979+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T14:57:31.980+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-28T14:57:31.981+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T14:57:32.003+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): transform_data> on 2023-04-28 14:57:29.074504+00:00
[2023-04-28T14:57:32.008+0000] {standard_task_runner.py:55} INFO - Started process 1927 to run task
[2023-04-28T14:57:32.012+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion_DAG', 'transform_data', 'manual__2023-04-28T14:57:29.074504+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpm30u6o8h']
[2023-04-28T14:57:32.015+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask transform_data
[2023-04-28T14:57:32.088+0000] {task_command.py:389} INFO - Running <TaskInstance: booking_ingestion_DAG.transform_data manual__2023-04-28T14:57:29.074504+00:00 [running]> on host 0e14e6a5e88f
[2023-04-28T14:57:32.348+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion_DAG
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T14:57:29.074504+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T14:57:29.074504+00:00
[2023-04-28T14:57:32.350+0000] {logging_mixin.py:137} INFO - ready for transform
[2023-04-28T14:57:32.387+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 37, in transform_data
    data = pd.merge(booking, client, on='client_id')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 627, in __init__
    _left = _validate_operand(left)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 2283, in _validate_operand
    f"Can only merge Series or DataFrame objects, a {type(obj)} was passed"
TypeError: Can only merge Series or DataFrame objects, a <class 'str'> was passed
[2023-04-28T14:57:32.408+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=booking_ingestion_DAG, task_id=transform_data, execution_date=20230428T145729, start_date=20230428T145731, end_date=20230428T145732
[2023-04-28T14:57:32.425+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task transform_data (Can only merge Series or DataFrame objects, a <class 'str'> was passed; 1927)
[2023-04-28T14:57:32.466+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-28T14:57:32.491+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
