[2023-04-28T14:48:46.846+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion_DAG.extract_data manual__2023-04-28T14:48:45.581102+00:00 [queued]>
[2023-04-28T14:48:46.860+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion_DAG.extract_data manual__2023-04-28T14:48:45.581102+00:00 [queued]>
[2023-04-28T14:48:46.861+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T14:48:46.862+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-28T14:48:46.863+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T14:48:46.880+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-28 14:48:45.581102+00:00
[2023-04-28T14:48:46.885+0000] {standard_task_runner.py:55} INFO - Started process 1685 to run task
[2023-04-28T14:48:46.889+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion_DAG', 'extract_data', 'manual__2023-04-28T14:48:45.581102+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmph98gvdpb']
[2023-04-28T14:48:46.891+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask extract_data
[2023-04-28T14:48:46.977+0000] {task_command.py:389} INFO - Running <TaskInstance: booking_ingestion_DAG.extract_data manual__2023-04-28T14:48:45.581102+00:00 [running]> on host 0e14e6a5e88f
[2023-04-28T14:48:47.258+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion_DAG
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T14:48:45.581102+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T14:48:45.581102+00:00
[2023-04-28T14:48:47.275+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-04-28T14:48:47.277+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 18, in extract_data
    context['ti'].xcom_push(key='my_data_1', value=booking)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2305, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-04-28T14:48:47.296+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=booking_ingestion_DAG, task_id=extract_data, execution_date=20230428T144845, start_date=20230428T144846, end_date=20230428T144847
[2023-04-28T14:48:47.312+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task extract_data (Object of type DataFrame is not JSON serializable; 1685)
[2023-04-28T14:48:47.342+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-28T14:48:47.370+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
